rootProject.name = "RacketClash"
include(
    "common:database",
    "common:ui:base",
    "common:ui:view",
    "common:state",
    "common:databaseApi",
    "common:model:addOrUpdateCategory",
    "common:model:addOrUpdateTeam",
    "common:model:addOrUpdateTournament",
    "common:model:addSchedule",
    "common:model:categories",
    "common:model:category",
    "common:model:schedule",
    "common:model:team",
    "common:model:teams",
    "common:model:tournaments",
    "desktop"
)