rootProject.name = "RacketClash"
include(
    "common:database",
    "common:ui",
    "common:util:state",
    "common:state",
    "common:model:addOrUpdateCategory",
    "common:model:addOrUpdatePlayer",
    "common:model:addOrUpdateRule",
    "common:model:addOrUpdateTeam",
    "common:model:addOrUpdateTournament",
    "common:model:addSchedule",
    "common:model:categories",
    "common:model:category",
    "common:model:players",
    "common:model:player",
    "common:model:schedule",
    "common:model:team",
    "common:model:teams",
    "common:model:tournaments",
    "common:model:start",
    "desktop"
)